# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd870075e5617961f0925800d515534b1edd7c2db8b30006c89be97b5af9318f0868c752ba199977ecc802b1700e1770f6e1f2d8061d15504ab0301e58056e9a

test:
  secret_key_base: 954e342fd29400e8f75ac9bb83d2fd5a6dd75ec19eb8435b0e6f8ca502f1aec3f64a2213d5df82b7ebc5a95a2f2b82009445459d5601c815ee0c9a1eb4a9804f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
